sulu_article.article:
    type: rest
    resource: Sulu\Bundle\ArticleBundle\Controller\ArticleController
    name_prefix: sulu_article.

sulu_article.article_page:
    type: rest
    resource: Sulu\Bundle\ArticleBundle\Controller\ArticlePageController
    name_prefix: sulu_article.

sulu_article.article.versioning:
    type: rest
    resource: Sulu\Bundle\ArticleBundle\Controller\VersionController
    name_prefix: sulu_article.
    parent: sulu_article.article
